# Generated by Django 4.2.1 on 2023-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.TextField(help_text='Напишите что нибудь...', max_length=500, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.TextField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
