# Generated by Django 4.2.1 on 2023-05-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_category_slug_alter_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(help_text='Напишите что нибудь...', max_length=20000, unique=True, verbose_name='Текст продукта'),
        ),
    ]
