# Generated by Django 4.2.1 on 2023-05-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Some desc', help_text='Напишите что нибудь...', max_length=20000, verbose_name='Текст продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(help_text='Напишите что нибудь...', max_length=1000, unique=True, verbose_name='Название продукта'),
        ),
    ]
