# Generated by Django 4.2.1 on 2023-05-12 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogue.product'),
        ),
    ]
