# Generated by Django 4.2.1 on 2023-05-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_product_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
