# Generated by Django 4.2.1 on 2023-05-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_product_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristic',
            field=models.TextField(blank=True, help_text='Напишите что нибудь...', max_length=2500, null=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='options',
            field=models.TextField(blank=True, help_text='Напишите что нибудь...', max_length=2500, null=True, verbose_name='Параметры'),
        ),
    ]
