# Generated by Django 4.2.1 on 2023-05-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0011_product_characteristic_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='catalogue.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='catalogue.category', verbose_name='Категория'),
        ),
    ]
