# Generated by Django 4.2.1 on 2023-05-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_category_products_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, verbose_name='ФИО Клиента')),
                ('phone_number', models.CharField(blank=True, max_length=70, verbose_name='Номер клиента')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name_plural': 'Заявки на звонок',
            },
        ),
    ]
